### PR TITLE
Upload to Bintray on any version 1 tags

### PR DESCRIPTION
**Pull request by fitzsia2**
## Summary
Use GitHub Actions to assemble, install, and upload library revisions tagged with "1.*" to Bintray+Maven.

## Implementation Details
`bintrayUsername` and `bintrayApiKey` need to be added to the repository secrets.

### CODE REVIEW

**Comment by davidbilik** [comment]
n0ice. So what is the workflow now? We develop, merge new stuff to `master` and when we want to upload a new version we push the tag `1.*` and this github actions are being run?

**Comment by fitzsia2** [comment]
Exactly. If we ever go to a version 2.x, we'll need to update the workflow YML.

**Comment by davidbilik** [comment]
And what is the reason in the limitation of the tag?

**Comment by fitzsia2** [comment]
I couldn't find any documentation for triggering on ANY tag create. The alternative would be to trigger on push to master

**Comment by davidbilik** [comment]
Ok, here we go!

**Pull request merged**
